package com.bjwg.main.model;

import com.bjwg.main.base.BaseVo;

/**
 * 地区记录v2
 * @ClassName: Area_V2 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-6-9 下午02:21:05
 */
public class Area_V2 extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1671044048463858634L;

	/**
     *
     * @mbggenerated
     */
    private Long areaId;

    /**
     * 名称
     * @mbggenerated
     */
    private String name;

    /**
     * 父级id
     * @mbggenerated
     */
    private Long parent;

    /**
     * 邮政编码
     * @mbggenerated
     */
    private Integer zipcode;

    /**
     * 百度城市编号
     * @mbggenerated
     */
    private Long baiduCode;

    /**
     * 扩展- 父级名称
     */
    private String parentName;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_AREA_V2.AREA_ID
     *
     * @return the value of HZD_AREA_V2.AREA_ID
     *
     * @mbggenerated
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_AREA_V2.AREA_ID
     *
     * @param areaId the value for HZD_AREA_V2.AREA_ID
     *
     * @mbggenerated
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_AREA_V2.NAME
     *
     * @return the value of HZD_AREA_V2.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_AREA_V2.NAME
     *
     * @param name the value for HZD_AREA_V2.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_AREA_V2.PARENT
     *
     * @return the value of HZD_AREA_V2.PARENT
     *
     * @mbggenerated
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_AREA_V2.PARENT
     *
     * @param parent the value for HZD_AREA_V2.PARENT
     *
     * @mbggenerated
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_AREA_V2.ZIPCODE
     *
     * @return the value of HZD_AREA_V2.ZIPCODE
     *
     * @mbggenerated
     */
    public Integer getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_AREA_V2.ZIPCODE
     *
     * @param zipcode the value for HZD_AREA_V2.ZIPCODE
     *
     * @mbggenerated
     */
    public void setZipcode(Integer zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_AREA_V2.BAIDU_CODE
     *
     * @return the value of HZD_AREA_V2.BAIDU_CODE
     *
     * @mbggenerated
     */
    public Long getBaiduCode() {
        return baiduCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_AREA_V2.BAIDU_CODE
     *
     * @param baiduCode the value for HZD_AREA_V2.BAIDU_CODE
     *
     * @mbggenerated
     */
    public void setBaiduCode(Long baiduCode) {
        this.baiduCode = baiduCode;
    }

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}
}