package com.bjwg.main.model;

import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 银行个人信息
 * @ClassName: BankPersonInfo 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-17 上午10:54:47
 */
public class BankPersonInfo extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = 7025229399616871344L;

	/**
     *
     * @mbggenerated
     */
    private Long personId;

    /**
     * 户名
     * @mbggenerated
     */
    private String name;

    /**
     * 身份证
     * @mbggenerated
     */
    private String idCard;

    /**
     * 创建时间
     * @mbggenerated
     */
    private Date ctime;

    /**
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_person_info.person_id
     *
     * @return the value of bjwg_bank_person_info.person_id
     *
     * @mbggenerated
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_person_info.person_id
     *
     * @param personId the value for bjwg_bank_person_info.person_id
     *
     * @mbggenerated
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_person_info.name
     *
     * @return the value of bjwg_bank_person_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_person_info.name
     *
     * @param name the value for bjwg_bank_person_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_person_info.id_card
     *
     * @return the value of bjwg_bank_person_info.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_person_info.id_card
     *
     * @param idCard the value for bjwg_bank_person_info.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_person_info.ctime
     *
     * @return the value of bjwg_bank_person_info.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_person_info.ctime
     *
     * @param ctime the value for bjwg_bank_person_info.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_person_info.user_id
     *
     * @return the value of bjwg_bank_person_info.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_person_info.user_id
     *
     * @param userId the value for bjwg_bank_person_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}