package com.bjwg.main.model;

import java.math.BigDecimal;
import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 附件记录表
 * @ClassName: FileUpload 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-6-1 下午08:15:44
 */
public class FileUpload extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = 794061309795727554L;

	/**
     * 主键
     * @mbggenerated
     */
    private Long uploadId;

    /**
     * 源文件名称
     * @mbggenerated
     */
    private String sourceName;

    /**
     * 路径
     * @mbggenerated
     */
    private String path;

    /**
     * 后缀名称
     * @mbggenerated
     */
    private String suffixName;

    /**
     * 文件大小
     * @mbggenerated
     */
    private BigDecimal fileSize;

    /**
     * 上传时间
     * @mbggenerated
     */
    private Date ctime;

    /**
     * 附件类型
     * @mbggenerated
     */
    private Short uploadType;

    /**
     * 外键，关联id
     * @mbggenerated
     */
    private Long relationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_FILE_UPLOAD.UPLOAD_ID
     *
     * @return the value of HZD_FILE_UPLOAD.UPLOAD_ID
     *
     * @mbggenerated
     */
    public Long getUploadId() {
        return uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_FILE_UPLOAD.UPLOAD_ID
     *
     * @param uploadId the value for HZD_FILE_UPLOAD.UPLOAD_ID
     *
     * @mbggenerated
     */
    public void setUploadId(Long uploadId) {
        this.uploadId = uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_FILE_UPLOAD.SOURCE_NAME
     *
     * @return the value of HZD_FILE_UPLOAD.SOURCE_NAME
     *
     * @mbggenerated
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_FILE_UPLOAD.SOURCE_NAME
     *
     * @param sourceName the value for HZD_FILE_UPLOAD.SOURCE_NAME
     *
     * @mbggenerated
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_FILE_UPLOAD.PATH
     *
     * @return the value of HZD_FILE_UPLOAD.PATH
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_FILE_UPLOAD.PATH
     *
     * @param path the value for HZD_FILE_UPLOAD.PATH
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_FILE_UPLOAD.SUFFIX_NAME
     *
     * @return the value of HZD_FILE_UPLOAD.SUFFIX_NAME
     *
     * @mbggenerated
     */
    public String getSuffixName() {
        return suffixName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_FILE_UPLOAD.SUFFIX_NAME
     *
     * @param suffixName the value for HZD_FILE_UPLOAD.SUFFIX_NAME
     *
     * @mbggenerated
     */
    public void setSuffixName(String suffixName) {
        this.suffixName = suffixName == null ? null : suffixName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_FILE_UPLOAD.FILE_SIZE
     *
     * @return the value of HZD_FILE_UPLOAD.FILE_SIZE
     *
     * @mbggenerated
     */
    public BigDecimal getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_FILE_UPLOAD.FILE_SIZE
     *
     * @param fileSize the value for HZD_FILE_UPLOAD.FILE_SIZE
     *
     * @mbggenerated
     */
    public void setFileSize(BigDecimal fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_FILE_UPLOAD.CTIME
     *
     * @return the value of HZD_FILE_UPLOAD.CTIME
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_FILE_UPLOAD.CTIME
     *
     * @param ctime the value for HZD_FILE_UPLOAD.CTIME
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_FILE_UPLOAD.UPLOAD_TYPE
     *
     * @return the value of HZD_FILE_UPLOAD.UPLOAD_TYPE
     *
     * @mbggenerated
     */
    public Short getUploadType() {
        return uploadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_FILE_UPLOAD.UPLOAD_TYPE
     *
     * @param uploadType the value for HZD_FILE_UPLOAD.UPLOAD_TYPE
     *
     * @mbggenerated
     */
    public void setUploadType(Short uploadType) {
        this.uploadType = uploadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_FILE_UPLOAD.RELATION_ID
     *
     * @return the value of HZD_FILE_UPLOAD.RELATION_ID
     *
     * @mbggenerated
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_FILE_UPLOAD.RELATION_ID
     *
     * @param relationId the value for HZD_FILE_UPLOAD.RELATION_ID
     *
     * @mbggenerated
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }
}