package com.bjwg.main.model;

import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 好友
 * @ClassName: Freinds 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-14 下午07:01:08
 */
public class Freinds extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = 7277747124458658965L;

	/**
     * 用户id
     * @mbggenerated
     */
    private Long myUserId;

    /**
     * 邀请的好友id
     * @mbggenerated
     */
    private Long freindId;

    /**
     * 类型 1:查找添加2:邀请添加（默认自动同意status:1，agree_time为用户注册时间）'
     * @mbggenerated
     */
    private Byte addType;

    /**
     * 发送时间
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * 发送的留言
     * @mbggenerated
     */
    private String sendRemark;

    /**
     * 状态 0:未处理 1:同意 2:不同意
     * @mbggenerated
     */
    private Byte status;

    /**
     * 同意时间
     * @mbggenerated
     */
    private Date agreeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_freinds.my_user_id
     *
     * @return the value of bjwg_freinds.my_user_id
     *
     * @mbggenerated
     */
    public Long getMyUserId() {
        return myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_freinds.my_user_id
     *
     * @param myUserId the value for bjwg_freinds.my_user_id
     *
     * @mbggenerated
     */
    public void setMyUserId(Long myUserId) {
        this.myUserId = myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_freinds.freind_id
     *
     * @return the value of bjwg_freinds.freind_id
     *
     * @mbggenerated
     */
    public Long getFreindId() {
        return freindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_freinds.freind_id
     *
     * @param freindId the value for bjwg_freinds.freind_id
     *
     * @mbggenerated
     */
    public void setFreindId(Long freindId) {
        this.freindId = freindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_freinds.add_type
     *
     * @return the value of bjwg_freinds.add_type
     *
     * @mbggenerated
     */
    public Byte getAddType() {
        return addType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_freinds.add_type
     *
     * @param addType the value for bjwg_freinds.add_type
     *
     * @mbggenerated
     */
    public void setAddType(Byte addType) {
        this.addType = addType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_freinds.send_time
     *
     * @return the value of bjwg_freinds.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_freinds.send_time
     *
     * @param sendTime the value for bjwg_freinds.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_freinds.send_remark
     *
     * @return the value of bjwg_freinds.send_remark
     *
     * @mbggenerated
     */
    public String getSendRemark() {
        return sendRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_freinds.send_remark
     *
     * @param sendRemark the value for bjwg_freinds.send_remark
     *
     * @mbggenerated
     */
    public void setSendRemark(String sendRemark) {
        this.sendRemark = sendRemark == null ? null : sendRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_freinds.status
     *
     * @return the value of bjwg_freinds.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_freinds.status
     *
     * @param status the value for bjwg_freinds.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_freinds.agree_time
     *
     * @return the value of bjwg_freinds.agree_time
     *
     * @mbggenerated
     */
    public Date getAgreeTime() {
        return agreeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_freinds.agree_time
     *
     * @param agreeTime the value for bjwg_freinds.agree_time
     *
     * @mbggenerated
     */
    public void setAgreeTime(Date agreeTime) {
        this.agreeTime = agreeTime;
    }
}