package com.bjwg.main.model;

import com.bjwg.main.base.BaseVo;

/**
 * 订单收货地址
 * @ClassName: OrderAddress 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-19 上午10:48:53
 */
public class OrderAddress extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = -8849094852086942767L;

	/**
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 省份 
     * @mbggenerated
     */
    private Long province;

    /**
     * 城市
     * @mbggenerated
     */
    private Long city;

    /**
     * 具体地址
     * @mbggenerated
     */
    private String address;

    /**
     * 联系人
     * @mbggenerated
     */
    private String linkMan;

    /**
     * 联系电话
     * @mbggenerated
     */
    private String linkPhone;

    /**
     * 备注
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order_address.order_id
     *
     * @return the value of bjwg_order_address.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order_address.order_id
     *
     * @param orderId the value for bjwg_order_address.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order_address.user_id
     *
     * @return the value of bjwg_order_address.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order_address.user_id
     *
     * @param userId the value for bjwg_order_address.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order_address.province
     *
     * @return the value of bjwg_order_address.province
     *
     * @mbggenerated
     */
    public Long getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order_address.province
     *
     * @param province the value for bjwg_order_address.province
     *
     * @mbggenerated
     */
    public void setProvince(Long province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order_address.city
     *
     * @return the value of bjwg_order_address.city
     *
     * @mbggenerated
     */
    public Long getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order_address.city
     *
     * @param city the value for bjwg_order_address.city
     *
     * @mbggenerated
     */
    public void setCity(Long city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order_address.address
     *
     * @return the value of bjwg_order_address.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order_address.address
     *
     * @param address the value for bjwg_order_address.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order_address.link_man
     *
     * @return the value of bjwg_order_address.link_man
     *
     * @mbggenerated
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order_address.link_man
     *
     * @param linkMan the value for bjwg_order_address.link_man
     *
     * @mbggenerated
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order_address.link_phone
     *
     * @return the value of bjwg_order_address.link_phone
     *
     * @mbggenerated
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order_address.link_phone
     *
     * @param linkPhone the value for bjwg_order_address.link_phone
     *
     * @mbggenerated
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone == null ? null : linkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order_address.remark
     *
     * @return the value of bjwg_order_address.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order_address.remark
     *
     * @param remark the value for bjwg_order_address.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}