package com.bjwg.main.model;

import java.math.BigDecimal;
import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 订单
 * @ClassName: Order 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-14 上午10:40:24
 */
public class Order extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = -7565060510201137989L;

	/**
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * 编号
     * @mbggenerated
     */
    private String orderCode;

    /**
     * 下单时间
     * @mbggenerated
     */
    private Date ctime;

    /**
     * 类型 1:抢购 2:屠宰寄送
     * @mbggenerated
     */
    private Byte type;

    /**
     * 状态 -1:已取消 1:未付款 2:付款中 3:已付款4:已选择处理方式5:已确认收货
     * @mbggenerated
     */
    private Byte status;

    /**
     * 数量
     * @mbggenerated
     */
    private Short num;

    /**
     * 单价
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * 总金额
     * @mbggenerated
     */
    private BigDecimal totalMoney;

    /**
     * 付款时间
     * @mbggenerated
     */
    private Date payTime;

    /**
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 商品名称
     * @mbggenerated
     */
    private String productName;

    /**
     * 付款方式 1:支付宝2:微信支付3:余额 4:银联
     * @mbggenerated
     */
    private Byte payType;

    /**
     * 关联id 目前存放抢购项目id
     * @mbggenerated
     */
    private Long relationId;

    /**
     * 关联名称
     * @mbggenerated
     */
    private String relationName;

    /**
     * 支付截止时间 ：下单1小时内要付款
     * @mbggenerated
     */
    private Date overTime;

    /**
     * 商品图片
     * @mbggenerated
     */
    private String productImg;

    /**
     * 子单id 默认-1.记录从本单中新增的子单id。目前只有屠宰配送才需记录。领取活猪不会生成订单费用记录
     * @mbggenerated
     */
    private Long subOrderId;

    /**
     * 确认收货时间
     * @mbggenerated
     */
    private Date confirmTime;
    
    /**
     * 预付款订单号（微信支付使用）
     */
    private String prepayOrderCode;
    
    /**
     * 是否显示 默认1显示 0不显示
     */
    private Byte isShow;
    
    /**
     * 扩展字段
     */
    private Long days;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.order_id
     *
     * @return the value of bjwg_order.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.order_id
     *
     * @param orderId the value for bjwg_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.order_code
     *
     * @return the value of bjwg_order.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.order_code
     *
     * @param orderCode the value for bjwg_order.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.ctime
     *
     * @return the value of bjwg_order.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.ctime
     *
     * @param ctime the value for bjwg_order.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.type
     *
     * @return the value of bjwg_order.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.type
     *
     * @param type the value for bjwg_order.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.status
     *
     * @return the value of bjwg_order.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.status
     *
     * @param status the value for bjwg_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.num
     *
     * @return the value of bjwg_order.num
     *
     * @mbggenerated
     */
    public Short getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.num
     *
     * @param num the value for bjwg_order.num
     *
     * @mbggenerated
     */
    public void setNum(Short num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.price
     *
     * @return the value of bjwg_order.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.price
     *
     * @param price the value for bjwg_order.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.total_money
     *
     * @return the value of bjwg_order.total_money
     *
     * @mbggenerated
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.total_money
     *
     * @param totalMoney the value for bjwg_order.total_money
     *
     * @mbggenerated
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.pay_time
     *
     * @return the value of bjwg_order.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.pay_time
     *
     * @param payTime the value for bjwg_order.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.user_id
     *
     * @return the value of bjwg_order.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.user_id
     *
     * @param userId the value for bjwg_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.remark
     *
     * @return the value of bjwg_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.remark
     *
     * @param remark the value for bjwg_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.product_name
     *
     * @return the value of bjwg_order.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.product_name
     *
     * @param productName the value for bjwg_order.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.pay_type
     *
     * @return the value of bjwg_order.pay_type
     *
     * @mbggenerated
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.pay_type
     *
     * @param payType the value for bjwg_order.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.relation_id
     *
     * @return the value of bjwg_order.relation_id
     *
     * @mbggenerated
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.relation_id
     *
     * @param relationId the value for bjwg_order.relation_id
     *
     * @mbggenerated
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.relation_name
     *
     * @return the value of bjwg_order.relation_name
     *
     * @mbggenerated
     */
    public String getRelationName() {
        return relationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.relation_name
     *
     * @param relationName the value for bjwg_order.relation_name
     *
     * @mbggenerated
     */
    public void setRelationName(String relationName) {
        this.relationName = relationName == null ? null : relationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.over_time
     *
     * @return the value of bjwg_order.over_time
     *
     * @mbggenerated
     */
    public Date getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.over_time
     *
     * @param overTime the value for bjwg_order.over_time
     *
     * @mbggenerated
     */
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.product_img
     *
     * @return the value of bjwg_order.product_img
     *
     * @mbggenerated
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.product_img
     *
     * @param productImg the value for bjwg_order.product_img
     *
     * @mbggenerated
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg == null ? null : productImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.sub_order_id
     *
     * @return the value of bjwg_order.sub_order_id
     *
     * @mbggenerated
     */
    public Long getSubOrderId() {
        return subOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.sub_order_id
     *
     * @param subOrderId the value for bjwg_order.sub_order_id
     *
     * @mbggenerated
     */
    public void setSubOrderId(Long subOrderId) {
        this.subOrderId = subOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.confirm_time
     *
     * @return the value of bjwg_order.confirm_time
     *
     * @mbggenerated
     */
    public Date getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.confirm_time
     *
     * @param confirmTime the value for bjwg_order.confirm_time
     *
     * @mbggenerated
     */
    public void setConfirmTime(Date confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_order.prepay_order_code
     *
     * @return the value of bjwg_order.prepay_order_code
     *
     * @mbggenerated
     */
    public String getPrepayOrderCode() {
        return prepayOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_order.prepay_order_code
     *
     * @param prepayOrderCode the value for bjwg_order.prepay_order_code
     *
     * @mbggenerated
     */
    public void setPrepayOrderCode(String prepayOrderCode) {
        this.prepayOrderCode = prepayOrderCode == null ? null : prepayOrderCode.trim();
    }

	public Long getDays() {
		return days;
	}

	public void setDays(Long days) {
		this.days = days;
	}

	public Byte getIsShow() {
		return isShow;
	}

	public void setIsShow(Byte isShow) {
		this.isShow = isShow;
	}
}