package com.bjwg.main.model;

import java.math.BigDecimal;
import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 支付表
 * @ClassName: Pay 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-9 下午04:02:33
 */
public class Pay extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3193767296132355833L;

	/**
     * 交易号
     * @mbggenerated
     */
    private String tradeNo;

    /**
     * 订单编号
     * @mbggenerated
     */
    private String orderCode;

    /**
     * 交易状态
     * @mbggenerated
     */
    private String tradeStatus;

    /**
     * 买家账号
     * @mbggenerated
     */
    private String buyer;

    /**
     * 卖家账号
     * @mbggenerated
     */
    private String seller;

    /**
     * 交易创建时间
     * @mbggenerated
     */
    private Date gmtCreateTime;

    /**
     * 交易完成时间
     * @mbggenerated
     */
    private Date gmtPayTime;

    /**
     * 总额
     * @mbggenerated
     */
    private BigDecimal totalMoney;

    /**
     * 失败信息
     * @mbggenerated
     */
    private String failMsg;

    /**
     * 付款方式  1：支付宝支付 2：微信支付 3:银联支付
     * @mbggenerated
     */
    private Byte payType;

    /**
     * 源数据
     * @mbggenerated
     */
    private String sourceData;
    
    //非表字段
    private String headImg;		//头像
    private String nickName;	//昵称
    private Integer count;		//购买数量
    private Long projectId;		//
    private String projectName;	//期名

    
    
    public Long getProjectId() {
		return projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	public String getHeadImg() {
		return headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}



	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.TRADE_NO
     *
     * @return the value of BJWG_PAY.TRADE_NO
     *
     * @mbggenerated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.TRADE_NO
     *
     * @param tradeNo the value for BJWG_PAY.TRADE_NO
     *
     * @mbggenerated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.ORDER_CODE
     *
     * @return the value of BJWG_PAY.ORDER_CODE
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.ORDER_CODE
     *
     * @param orderCode the value for BJWG_PAY.ORDER_CODE
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.TRADE_STATUS
     *
     * @return the value of BJWG_PAY.TRADE_STATUS
     *
     * @mbggenerated
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.TRADE_STATUS
     *
     * @param tradeStatus the value for BJWG_PAY.TRADE_STATUS
     *
     * @mbggenerated
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus == null ? null : tradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.BUYER
     *
     * @return the value of BJWG_PAY.BUYER
     *
     * @mbggenerated
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.BUYER
     *
     * @param buyer the value for BJWG_PAY.BUYER
     *
     * @mbggenerated
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer == null ? null : buyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.SELLER
     *
     * @return the value of BJWG_PAY.SELLER
     *
     * @mbggenerated
     */
    public String getSeller() {
        return seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.SELLER
     *
     * @param seller the value for BJWG_PAY.SELLER
     *
     * @mbggenerated
     */
    public void setSeller(String seller) {
        this.seller = seller == null ? null : seller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.GMT_CREATE_TIME
     *
     * @return the value of BJWG_PAY.GMT_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getGmtCreateTime() {
        return gmtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.GMT_CREATE_TIME
     *
     * @param gmtCreateTime the value for BJWG_PAY.GMT_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setGmtCreateTime(Date gmtCreateTime) {
        this.gmtCreateTime = gmtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.GMT_PAY_TIME
     *
     * @return the value of BJWG_PAY.GMT_PAY_TIME
     *
     * @mbggenerated
     */
    public Date getGmtPayTime() {
        return gmtPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.GMT_PAY_TIME
     *
     * @param gmtPayTime the value for BJWG_PAY.GMT_PAY_TIME
     *
     * @mbggenerated
     */
    public void setGmtPayTime(Date gmtPayTime) {
        this.gmtPayTime = gmtPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.TOTAL_MONEY
     *
     * @return the value of BJWG_PAY.TOTAL_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.TOTAL_MONEY
     *
     * @param totalMoney the value for BJWG_PAY.TOTAL_MONEY
     *
     * @mbggenerated
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.FAIL_MSG
     *
     * @return the value of BJWG_PAY.FAIL_MSG
     *
     * @mbggenerated
     */
    public String getFailMsg() {
        return failMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.FAIL_MSG
     *
     * @param failMsg the value for BJWG_PAY.FAIL_MSG
     *
     * @mbggenerated
     */
    public void setFailMsg(String failMsg) {
        this.failMsg = failMsg == null ? null : failMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.PAY_TYPE
     *
     * @return the value of BJWG_PAY.PAY_TYPE
     *
     * @mbggenerated
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.PAY_TYPE
     *
     * @param payType the value for BJWG_PAY.PAY_TYPE
     *
     * @mbggenerated
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_PAY.SOURCE_DATA
     *
     * @return the value of BJWG_PAY.SOURCE_DATA
     *
     * @mbggenerated
     */
    public String getSourceData() {
        return sourceData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_PAY.SOURCE_DATA
     *
     * @param sourceData the value for BJWG_PAY.SOURCE_DATA
     *
     * @mbggenerated
     */
    public void setSourceData(String sourceData) {
        this.sourceData = sourceData == null ? null : sourceData.trim();
    }
}