package com.bjwg.main.model;

import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 服务协议
 * @ClassName: ServiceProtocol 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-22 上午10:46:58
 */
public class ServiceProtocol extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5488381530478942333L;

	/**
     *
     * @mbggenerated
     */
    private Long spId;

    /**
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * 类型 对应字典里的编号为BJWG_SERVICE_PROTOCOL.TYPE
     * @mbggenerated
     */
    private Byte type;

    /**
     * 内容
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_service_protocol.sp_id
     *
     * @return the value of bjwg_service_protocol.sp_id
     *
     * @mbggenerated
     */
    public Long getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_service_protocol.sp_id
     *
     * @param spId the value for bjwg_service_protocol.sp_id
     *
     * @mbggenerated
     */
    public void setSpId(Long spId) {
        this.spId = spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_service_protocol.ctime
     *
     * @return the value of bjwg_service_protocol.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_service_protocol.ctime
     *
     * @param ctime the value for bjwg_service_protocol.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_service_protocol.type
     *
     * @return the value of bjwg_service_protocol.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_service_protocol.type
     *
     * @param type the value for bjwg_service_protocol.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_service_protocol.content
     *
     * @return the value of bjwg_service_protocol.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_service_protocol.content
     *
     * @param content the value for bjwg_service_protocol.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}