package com.bjwg.main.model;

import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 用户预标记录
 * @ClassName: UserPreorder 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-19 下午02:54:09
 */
public class UserPreorder extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8072950370456031030L;

	/**
     * 抢购项目id
     * @mbggenerated
     */
    private Long projectId;

    /**
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     *
     * @mbggenerated
     */
    private Date ctime;
    /**
     * 数量
     * @mbggenerated
     */
    private Integer num;
    
    /**
     * 扩展字段 - 抢购项目名称
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_preorder.project_id
     *
     * @return the value of bjwg_user_preorder.project_id
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_preorder.project_id
     *
     * @param projectId the value for bjwg_user_preorder.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_preorder.user_id
     *
     * @return the value of bjwg_user_preorder.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_preorder.user_id
     *
     * @param userId the value for bjwg_user_preorder.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_preorder.ctime
     *
     * @return the value of bjwg_user_preorder.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_preorder.ctime
     *
     * @param ctime the value for bjwg_user_preorder.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}
}