package com.bjwg.main.model;

import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 用户扩展记录
 * @author Administrator
 *
 */
public class UserExt extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6959129361325879818L;

	/**
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 最近一次看得公告id，默认0
     * @mbggenerated
     */
    private Long lastButtinId;

    /**
     * 设置类型 默认1:每期固定抢标2:定制哪期抢标
     * @mbggenerated
     */
    private Byte settingType;

    /**
     * 设置时间
     * @mbggenerated
     */
    private Date settingTime;
    /**
     * 设置值
     * @mbggenerated
     */
    private Integer settingValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_ext.user_id
     *
     * @return the value of bjwg_user_ext.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_ext.user_id
     *
     * @param userId the value for bjwg_user_ext.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_ext.last_buttin_id
     *
     * @return the value of bjwg_user_ext.last_buttin_id
     *
     * @mbggenerated
     */
    public Long getLastButtinId() {
        return lastButtinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_ext.last_buttin_id
     *
     * @param lastButtinId the value for bjwg_user_ext.last_buttin_id
     *
     * @mbggenerated
     */
    public void setLastButtinId(Long lastButtinId) {
        this.lastButtinId = lastButtinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_ext.setting_type
     *
     * @return the value of bjwg_user_ext.setting_type
     *
     * @mbggenerated
     */
    public Byte getSettingType() {
        return settingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_ext.setting_type
     *
     * @param settingType the value for bjwg_user_ext.setting_type
     *
     * @mbggenerated
     */
    public void setSettingType(Byte settingType) {
        this.settingType = settingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_ext.setting_time
     *
     * @return the value of bjwg_user_ext.setting_time
     *
     * @mbggenerated
     */
    public Date getSettingTime() {
        return settingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_ext.setting_time
     *
     * @param settingTime the value for bjwg_user_ext.setting_time
     *
     * @mbggenerated
     */
    public void setSettingTime(Date settingTime) {
        this.settingTime = settingTime;
    }

	public Integer getSettingValue() {
		return settingValue;
	}

	public void setSettingValue(Integer settingValue) {
		this.settingValue = settingValue;
	}
}