package com.bjwg.main.model;

import com.bjwg.main.base.BaseVo;

/**
 * 用户地址
 * @ClassName: UserAddress 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-17 下午06:28:12
 */
public class UserAddress extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4510928536312791556L;

	/**
     *
     * @mbggenerated
     */
    private Long addressId;

    /**
     * 联系人
     * @mbggenerated
     */
    private String contactMan;

    /**
     * 联系电话
     * @mbggenerated
     */
    private String contactPhone;

    /**
     * 省份
     * @mbggenerated
     */
    private Long province;

    /**
     * 城市
     * @mbggenerated
     */
    private Long city;

    /**
     * 地址
     * @mbggenerated
     */
    private String address;

    /**
     * 是否默认
     * @mbggenerated
     */
    private Byte isDefault;

    /**
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_address.address_id
     *
     * @return the value of bjwg_user_address.address_id
     *
     * @mbggenerated
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_address.address_id
     *
     * @param addressId the value for bjwg_user_address.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_address.contact_man
     *
     * @return the value of bjwg_user_address.contact_man
     *
     * @mbggenerated
     */
    public String getContactMan() {
        return contactMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_address.contact_man
     *
     * @param contactMan the value for bjwg_user_address.contact_man
     *
     * @mbggenerated
     */
    public void setContactMan(String contactMan) {
        this.contactMan = contactMan == null ? null : contactMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_address.contact_phone
     *
     * @return the value of bjwg_user_address.contact_phone
     *
     * @mbggenerated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_address.contact_phone
     *
     * @param contactPhone the value for bjwg_user_address.contact_phone
     *
     * @mbggenerated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_address.province
     *
     * @return the value of bjwg_user_address.province
     *
     * @mbggenerated
     */
    public Long getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_address.province
     *
     * @param province the value for bjwg_user_address.province
     *
     * @mbggenerated
     */
    public void setProvince(Long province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_address.city
     *
     * @return the value of bjwg_user_address.city
     *
     * @mbggenerated
     */
    public Long getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_address.city
     *
     * @param city the value for bjwg_user_address.city
     *
     * @mbggenerated
     */
    public void setCity(Long city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_address.address
     *
     * @return the value of bjwg_user_address.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_address.address
     *
     * @param address the value for bjwg_user_address.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_address.is_default
     *
     * @return the value of bjwg_user_address.is_default
     *
     * @mbggenerated
     */
    public Byte getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_address.is_default
     *
     * @param isDefault the value for bjwg_user_address.is_default
     *
     * @mbggenerated
     */
    public void setIsDefault(Byte isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_address.user_id
     *
     * @return the value of bjwg_user_address.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_address.user_id
     *
     * @param userId the value for bjwg_user_address.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}