package com.bjwg.main.model;

import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 验证码表
 * @ClassName: VerifyPhone 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-6-9 下午02:07:26
 */
public class VerifyPhone extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = -1385754287035735805L;

	/**
     *
     * @mbggenerated
     */
    private Long verifyPhoneId;

    /**
     * 电话号码
     * @mbggenerated
     */
    private Long phoneNo;

    /**
     * 验证码
     * @mbggenerated
     */
    private String verifyCode;

    /**
     * 发送时间
     * @mbggenerated
     */
    private Date ctime;

    /**
     * 用户id
     * @mbggenerated
     */
    private Long userId;

    /**
     * 验证码类型
     * @mbggenerated
     */
    private Short type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_VERIFY_PHONE.VERIFY_PHONE_ID
     *
     * @return the value of HZD_VERIFY_PHONE.VERIFY_PHONE_ID
     *
     * @mbggenerated
     */
    public Long getVerifyPhoneId() {
        return verifyPhoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_VERIFY_PHONE.VERIFY_PHONE_ID
     *
     * @param verifyPhoneId the value for HZD_VERIFY_PHONE.VERIFY_PHONE_ID
     *
     * @mbggenerated
     */
    public void setVerifyPhoneId(Long verifyPhoneId) {
        this.verifyPhoneId = verifyPhoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_VERIFY_PHONE.PHONE_NO
     *
     * @return the value of HZD_VERIFY_PHONE.PHONE_NO
     *
     * @mbggenerated
     */
    public Long getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_VERIFY_PHONE.PHONE_NO
     *
     * @param phoneNo the value for HZD_VERIFY_PHONE.PHONE_NO
     *
     * @mbggenerated
     */
    public void setPhoneNo(Long phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_VERIFY_PHONE.VERIFY_CODE
     *
     * @return the value of HZD_VERIFY_PHONE.VERIFY_CODE
     *
     * @mbggenerated
     */
    public String getVerifyCode() {
        return verifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_VERIFY_PHONE.VERIFY_CODE
     *
     * @param verifyCode the value for HZD_VERIFY_PHONE.VERIFY_CODE
     *
     * @mbggenerated
     */
    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode == null ? null : verifyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_VERIFY_PHONE.CTIME
     *
     * @return the value of HZD_VERIFY_PHONE.CTIME
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_VERIFY_PHONE.CTIME
     *
     * @param ctime the value for HZD_VERIFY_PHONE.CTIME
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_VERIFY_PHONE.USER_ID
     *
     * @return the value of HZD_VERIFY_PHONE.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_VERIFY_PHONE.USER_ID
     *
     * @param userId the value for HZD_VERIFY_PHONE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_VERIFY_PHONE.TYPE
     *
     * @return the value of HZD_VERIFY_PHONE.TYPE
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_VERIFY_PHONE.TYPE
     *
     * @param type the value for HZD_VERIFY_PHONE.TYPE
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }
}