package com.bjwg.main.model;

import java.math.BigDecimal;

import com.bjwg.main.base.BaseVo;

/**
 * 个人钱包记录
 * @ClassName: Wallet 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-9 下午03:53:43
 */
public class Wallet extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3283391110038834182L;

	/**
     *
     * @mbggenerated
     */
    private Long walletId;

    /**
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 余额
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * 状态 默认为1正常
     * @mbggenerated
     */
    private Short status;

    /**
    * 支付密码
     * @mbggenerated
     */
    private String payPassword;

    /**
     * 支付密码错误信息
     * @mbggenerated
     */
    private String json;

    /**
     * 扩展字段 - 卡数
     */
    private Short cardNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET.WALLET_ID
     *
     * @return the value of BJWG_WALLET.WALLET_ID
     *
     * @mbggenerated
     */
    public Long getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET.WALLET_ID
     *
     * @param walletId the value for BJWG_WALLET.WALLET_ID
     *
     * @mbggenerated
     */
    public void setWalletId(Long walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET.USER_ID
     *
     * @return the value of BJWG_WALLET.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET.USER_ID
     *
     * @param userId the value for BJWG_WALLET.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET.MONEY
     *
     * @return the value of BJWG_WALLET.MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET.MONEY
     *
     * @param money the value for BJWG_WALLET.MONEY
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET.STATUS
     *
     * @return the value of BJWG_WALLET.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET.STATUS
     *
     * @param status the value for BJWG_WALLET.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET.PAY_PASSWORD
     *
     * @return the value of BJWG_WALLET.PAY_PASSWORD
     *
     * @mbggenerated
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET.PAY_PASSWORD
     *
     * @param payPassword the value for BJWG_WALLET.PAY_PASSWORD
     *
     * @mbggenerated
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET.JSON
     *
     * @return the value of BJWG_WALLET.JSON
     *
     * @mbggenerated
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET.JSON
     *
     * @param json the value for BJWG_WALLET.JSON
     *
     * @mbggenerated
     */
    public void setJson(String json) {
        this.json = json == null ? null : json.trim();
    }

	public Short getCardNumber() {
		return cardNumber;
	}

	public void setCardNumber(Short cardNumber) {
		this.cardNumber = cardNumber;
	}

}