package com.bjwg.main.model;

import java.math.BigDecimal;

import com.bjwg.main.base.BaseVo;
/**
 * 用户余额联合银行卡
 * @ClassName: Balance 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-6-11 下午03:36:50
 */
public class WalletAndBankCard extends BaseVo{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4871958182960503584L;

	/**
     *
     * @mbggenerated
     */
    private Long walletId;

    /**
     * 用户id
     * @mbggenerated
     */
    private Long userId;

    /**
     * 余额
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * 状态
     * @mbggenerated
     */
    private Byte status;

    /**
     * 支付密码
     * @mbggenerated
     */
    private String payPassword;
    /**
     * 
     * @mbggenerated
     */
    private String json;
    
    
    /**
    *
    * @mbggenerated
    */
   private Long cardId;

   /**
    * 卡号
    * @mbggenerated
    */
   private String cardNo;

   /**
    * 户名
    * @mbggenerated
    */
   private String accountName;

   /**
    * 对公对私
    * @mbggenerated
    */
   private Byte cardType;

   /**
    * 银行代号
    * @mbggenerated
    */
   private String bankCode;

   /**
    * 银行名称
    * @mbggenerated
    */
   private String bank;

   /**
    * 身份证号
    * @mbggenerated
    */
   private String idCard;



    /**
     *
     * @mbggenerated
     */
    public Long getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_BALANCE.BALANCE_ID
     *
     * @param balanceId the value for HZD_BALANCE.BALANCE_ID
     *
     * @mbggenerated
     */
    public void setWalletId(Long walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_BALANCE.USER_ID
     *
     * @return the value of HZD_BALANCE.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_BALANCE.USER_ID
     *
     * @param userId the value for HZD_BALANCE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_BALANCE.MONEY
     *
     * @return the value of HZD_BALANCE.MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_BALANCE.MONEY
     *
     * @param money the value for HZD_BALANCE.MONEY
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_BALANCE.STATUS
     *
     * @return the value of HZD_BALANCE.STATUS
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_BALANCE.STATUS
     *
     * @param status the value for HZD_BALANCE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HZD_BALANCE.PAY_PASSWORD
     *
     * @return the value of HZD_BALANCE.PAY_PASSWORD
     *
     * @mbggenerated
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HZD_BALANCE.PAY_PASSWORD
     *
     * @param payPassword the value for HZD_BALANCE.PAY_PASSWORD
     *
     * @mbggenerated
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }


	public Long getCardId() {
		return cardId;
	}

	public void setCardId(Long cardId) {
		this.cardId = cardId;
	}

	public String getCardNo() {
		return cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public Byte getCardType() {
		return cardType;
	}

	public void setCardType(Byte cardType) {
		this.cardType = cardType;
	}

	public String getBankCode() {
		return bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public String getBank() {
		return bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getIdCard() {
		return idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getJson() {
		return json;
	}

	public void setJson(String json) {
		this.json = json;
	}
}