package com.bjwg.main.model;

import java.math.BigDecimal;
import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 钱包变更记录
 * @ClassName: WalletChange 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-9 下午03:52:06
 */
public class WalletChange extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5384532794832728642L;

	/**
     *
     * @mbggenerated
     */
    private Long walletChangeId;

    /**
     * 钱包记录id
     * @mbggenerated
     */
    private Long walletId;

    /**
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 变更前金额
     * @mbggenerated
     */
    private BigDecimal beforeMoney;

    /**
     * 变更金额
     * @mbggenerated
     */
    private BigDecimal changeMoney;

    /**
     * 变更后金额
     * @mbggenerated
     */
    private BigDecimal afterMoney;

    /**
     * 变更类型1:消费2:收入
     * @mbggenerated
     */
    private Byte changeType;

    /**
     * 变更时间
     * @mbggenerated
     */
    private Date changeTime;

    /**
     * 关联id
     * @mbggenerated
     */
    private Long relationId;

    /**
     * 关联类型 1:抢购购买2:委托寄卖3:提现4:收益
     * @mbggenerated
     */
    private Byte relationType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET_CHANGE.WALLET_CHANGE_ID
     *
     * @return the value of BJWG_WALLET_CHANGE.WALLET_CHANGE_ID
     *
     * @mbggenerated
     */
    public Long getWalletChangeId() {
        return walletChangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET_CHANGE.WALLET_CHANGE_ID
     *
     * @param walletChangeId the value for BJWG_WALLET_CHANGE.WALLET_CHANGE_ID
     *
     * @mbggenerated
     */
    public void setWalletChangeId(Long walletChangeId) {
        this.walletChangeId = walletChangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET_CHANGE.WALLET_ID
     *
     * @return the value of BJWG_WALLET_CHANGE.WALLET_ID
     *
     * @mbggenerated
     */
    public Long getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET_CHANGE.WALLET_ID
     *
     * @param walletId the value for BJWG_WALLET_CHANGE.WALLET_ID
     *
     * @mbggenerated
     */
    public void setWalletId(Long walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET_CHANGE.USER_ID
     *
     * @return the value of BJWG_WALLET_CHANGE.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET_CHANGE.USER_ID
     *
     * @param userId the value for BJWG_WALLET_CHANGE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET_CHANGE.BEFORE_MONEY
     *
     * @return the value of BJWG_WALLET_CHANGE.BEFORE_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getBeforeMoney() {
        return beforeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET_CHANGE.BEFORE_MONEY
     *
     * @param beforeMoney the value for BJWG_WALLET_CHANGE.BEFORE_MONEY
     *
     * @mbggenerated
     */
    public void setBeforeMoney(BigDecimal beforeMoney) {
        this.beforeMoney = beforeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET_CHANGE.CHANGE_MONEY
     *
     * @return the value of BJWG_WALLET_CHANGE.CHANGE_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getChangeMoney() {
        return changeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET_CHANGE.CHANGE_MONEY
     *
     * @param changeMoney the value for BJWG_WALLET_CHANGE.CHANGE_MONEY
     *
     * @mbggenerated
     */
    public void setChangeMoney(BigDecimal changeMoney) {
        this.changeMoney = changeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET_CHANGE.AFTER_MONEY
     *
     * @return the value of BJWG_WALLET_CHANGE.AFTER_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getAfterMoney() {
        return afterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET_CHANGE.AFTER_MONEY
     *
     * @param afterMoney the value for BJWG_WALLET_CHANGE.AFTER_MONEY
     *
     * @mbggenerated
     */
    public void setAfterMoney(BigDecimal afterMoney) {
        this.afterMoney = afterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET_CHANGE.CHANGE_TYPE
     *
     * @return the value of BJWG_WALLET_CHANGE.CHANGE_TYPE
     *
     * @mbggenerated
     */
    public Byte getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET_CHANGE.CHANGE_TYPE
     *
     * @param changeType the value for BJWG_WALLET_CHANGE.CHANGE_TYPE
     *
     * @mbggenerated
     */
    public void setChangeType(Byte changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET_CHANGE.CHANGE_TIME
     *
     * @return the value of BJWG_WALLET_CHANGE.CHANGE_TIME
     *
     * @mbggenerated
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET_CHANGE.CHANGE_TIME
     *
     * @param changeTime the value for BJWG_WALLET_CHANGE.CHANGE_TIME
     *
     * @mbggenerated
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET_CHANGE.RELATION_ID
     *
     * @return the value of BJWG_WALLET_CHANGE.RELATION_ID
     *
     * @mbggenerated
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET_CHANGE.RELATION_ID
     *
     * @param relationId the value for BJWG_WALLET_CHANGE.RELATION_ID
     *
     * @mbggenerated
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WALLET_CHANGE.RELATION_TYPE
     *
     * @return the value of BJWG_WALLET_CHANGE.RELATION_TYPE
     *
     * @mbggenerated
     */
    public Byte getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WALLET_CHANGE.RELATION_TYPE
     *
     * @param relationType the value for BJWG_WALLET_CHANGE.RELATION_TYPE
     *
     * @mbggenerated
     */
    public void setRelationType(Byte relationType) {
        this.relationType = relationType;
    }
}