package com.bjwg.main.model;

import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 微信表
 * @ClassName: WeiXinUser 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-8 下午08:20:42
 */
public class WeiXinUser extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5305322949065147217L;

	/**
     * 唯一标识
     * @mbggenerated
     */
    private String unionid;

    /**
     * 用户id
     * @mbggenerated
     */
    private Long userId;

    /**
     * 昵称
     * @mbggenerated
     */
    private String nickname;

    /**
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * 特权
     * @mbggenerated
     */
    private String privilege;
    
    /**
     * 扩展-性别
     */
    private String sex;
    /**
     * 扩展-省份
     */
    private String province;
    /**
     * 扩展-城市
     */
    private String city;
    /**
     * 扩展-头像
     */
    private String headImg;
    /**
     * 扩展-国家
     */
    private String country;
    /**
     * 扩展-时间
     */
    private Date ctime;
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WEIXINUSER.UNIONID
     *
     * @return the value of BJWG_WEIXINUSER.UNIONID
     *
     * @mbggenerated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WEIXINUSER.UNIONID
     *
     * @param unionid the value for BJWG_WEIXINUSER.UNIONID
     *
     * @mbggenerated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WEIXINUSER.USER_ID
     *
     * @return the value of BJWG_WEIXINUSER.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WEIXINUSER.USER_ID
     *
     * @param userId the value for BJWG_WEIXINUSER.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WEIXINUSER.NICKNAME
     *
     * @return the value of BJWG_WEIXINUSER.NICKNAME
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WEIXINUSER.NICKNAME
     *
     * @param nickname the value for BJWG_WEIXINUSER.NICKNAME
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WEIXINUSER.OPENID
     *
     * @return the value of BJWG_WEIXINUSER.OPENID
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WEIXINUSER.OPENID
     *
     * @param openid the value for BJWG_WEIXINUSER.OPENID
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJWG_WEIXINUSER.PRIVILEGE
     *
     * @return the value of BJWG_WEIXINUSER.PRIVILEGE
     *
     * @mbggenerated
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJWG_WEIXINUSER.PRIVILEGE
     *
     * @param privilege the value for BJWG_WEIXINUSER.PRIVILEGE
     *
     * @mbggenerated
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege == null ? null : privilege.trim();
    }

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getHeadImg() {
		return headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Date getCtime() {
		return ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}
}