package com.bjwg.main.model;

import java.math.BigDecimal;
import java.util.Date;

import com.bjwg.main.base.BaseVo;

/**
 * 提现记录
 * @ClassName: WithDrawals 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-16 下午03:44:36
 */
public class WithDrawals extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = -2178432087941651901L;

	/**
     *
     * @mbggenerated
     */
    private Long withwradalsId;

    /**
     * 提现金额
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * 提现时间
     * @mbggenerated
     */
    private Date ctime;

    /**
     * 户名
     * @mbggenerated
     */
    private String accountName;

    /**
     * 银行代号
     * @mbggenerated
     */
    private String bankCode;

    /**
     * 银行
     * @mbggenerated
     */
    private String bank;

    /**
     * 身份证号
     * @mbggenerated
     */
    private String idCard;

    /**
     * 用户id
     * @mbggenerated
     */
    private Long userId;

    /**
     * 用户昵称
     * @mbggenerated
     */
    private String username;

    /**
     * 状态
     * @mbggenerated
     */
    private Byte status;

    /**
     * 审核人
     * @mbggenerated
     */
    private String auditingMan;

    /**
     * 审核人id
     * @mbggenerated
     */
    private Long auditingManId;

    /**
     *
     * @mbggenerated
     */
    private Date auditingTime;

    /**
     * 备注
     * @mbggenerated
     */
    private String remark;

    /**
     * 钱包id
     * @mbggenerated
     */
    private Long walletId;

    /**
     * 银行卡号id
     * @mbggenerated
     */
    private Long cardId;

    /**
     * 卡类型
     * @mbggenerated
     */
    private Byte cardType;
    
    /**
     * 扩展 - 格式化的时间
     */
    private String fmtCTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.withwradals_id
     *
     * @return the value of bjwg_withdrawals.withwradals_id
     *
     * @mbggenerated
     */
    public Long getWithwradalsId() {
        return withwradalsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.withwradals_id
     *
     * @param withwradalsId the value for bjwg_withdrawals.withwradals_id
     *
     * @mbggenerated
     */
    public void setWithwradalsId(Long withwradalsId) {
        this.withwradalsId = withwradalsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.money
     *
     * @return the value of bjwg_withdrawals.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.money
     *
     * @param money the value for bjwg_withdrawals.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.ctime
     *
     * @return the value of bjwg_withdrawals.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.ctime
     *
     * @param ctime the value for bjwg_withdrawals.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.account_name
     *
     * @return the value of bjwg_withdrawals.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.account_name
     *
     * @param accountName the value for bjwg_withdrawals.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.bank_code
     *
     * @return the value of bjwg_withdrawals.bank_code
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.bank_code
     *
     * @param bankCode the value for bjwg_withdrawals.bank_code
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.bank
     *
     * @return the value of bjwg_withdrawals.bank
     *
     * @mbggenerated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.bank
     *
     * @param bank the value for bjwg_withdrawals.bank
     *
     * @mbggenerated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.ID_card
     *
     * @return the value of bjwg_withdrawals.ID_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.ID_card
     *
     * @param idCard the value for bjwg_withdrawals.ID_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.user_id
     *
     * @return the value of bjwg_withdrawals.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.user_id
     *
     * @param userId the value for bjwg_withdrawals.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.username
     *
     * @return the value of bjwg_withdrawals.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.username
     *
     * @param username the value for bjwg_withdrawals.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.status
     *
     * @return the value of bjwg_withdrawals.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.status
     *
     * @param status the value for bjwg_withdrawals.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.auditing_man
     *
     * @return the value of bjwg_withdrawals.auditing_man
     *
     * @mbggenerated
     */
    public String getAuditingMan() {
        return auditingMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.auditing_man
     *
     * @param auditingMan the value for bjwg_withdrawals.auditing_man
     *
     * @mbggenerated
     */
    public void setAuditingMan(String auditingMan) {
        this.auditingMan = auditingMan == null ? null : auditingMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.auditing_man_id
     *
     * @return the value of bjwg_withdrawals.auditing_man_id
     *
     * @mbggenerated
     */
    public Long getAuditingManId() {
        return auditingManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.auditing_man_id
     *
     * @param auditingManId the value for bjwg_withdrawals.auditing_man_id
     *
     * @mbggenerated
     */
    public void setAuditingManId(Long auditingManId) {
        this.auditingManId = auditingManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.auditing_time
     *
     * @return the value of bjwg_withdrawals.auditing_time
     *
     * @mbggenerated
     */
    public Date getAuditingTime() {
        return auditingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.auditing_time
     *
     * @param auditingTime the value for bjwg_withdrawals.auditing_time
     *
     * @mbggenerated
     */
    public void setAuditingTime(Date auditingTime) {
        this.auditingTime = auditingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.remark
     *
     * @return the value of bjwg_withdrawals.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.remark
     *
     * @param remark the value for bjwg_withdrawals.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.wallet_id
     *
     * @return the value of bjwg_withdrawals.wallet_id
     *
     * @mbggenerated
     */
    public Long getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.wallet_id
     *
     * @param walletId the value for bjwg_withdrawals.wallet_id
     *
     * @mbggenerated
     */
    public void setWalletId(Long walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.card_id
     *
     * @return the value of bjwg_withdrawals.card_id
     *
     * @mbggenerated
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.card_id
     *
     * @param cardId the value for bjwg_withdrawals.card_id
     *
     * @mbggenerated
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_withdrawals.card_type
     *
     * @return the value of bjwg_withdrawals.card_type
     *
     * @mbggenerated
     */
    public Byte getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_withdrawals.card_type
     *
     * @param cardType the value for bjwg_withdrawals.card_type
     *
     * @mbggenerated
     */
    public void setCardType(Byte cardType) {
        this.cardType = cardType;
    }

	public String getFmtCTime() {
		return fmtCTime;
	}

	public void setFmtCTime(String fmtCTime) {
		this.fmtCTime = fmtCTime;
	}
}