package com.bjwg.main.dao;

import com.bjwg.main.model.BankCard;
import com.bjwg.main.model.BankCardExample;
import java.util.List;

public interface BankCardDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_BANK_CARD
     *
     * @mbggenerated
     */
    int countByExample(BankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_BANK_CARD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_BANK_CARD
     *
     * @mbggenerated
     */
    int insert(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_BANK_CARD
     *
     * @mbggenerated
     */
    int insertSelective(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_BANK_CARD
     *
     * @mbggenerated
     */
    List<BankCard> selectByExample(BankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_BANK_CARD
     *
     * @mbggenerated
     */
    BankCard selectByPrimaryKey(Long cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_BANK_CARD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_BANK_CARD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BankCard record);
}