package com.bjwg.main.dao;

import com.bjwg.main.model.Info;
import com.bjwg.main.model.InfoExample;
import java.util.List;

public interface InfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_info
     *
     * @mbggenerated
     */
    int countByExample(InfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_info
     *
     * @mbggenerated
     */
    int insert(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_info
     *
     * @mbggenerated
     */
    int insertSelective(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_info
     *
     * @mbggenerated
     */
    List<Info> selectByExampleWithBLOBs(InfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_info
     *
     * @mbggenerated
     */
    List<Info> selectByExample(InfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_info
     *
     * @mbggenerated
     */
    Info selectByPrimaryKey(Long infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Info record);
    
    List<Info> selectNear(Long infoId);
    
    
}