package com.bjwg.main.dao;

import com.bjwg.main.model.Message;
import com.bjwg.main.model.MessageExample;
import java.util.List;

public interface MessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_message
     *
     * @mbggenerated
     */
    int countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long messageId);
    
    int deleteByUserId(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_message
     *
     * @mbggenerated
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_message
     *
     * @mbggenerated
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_message
     *
     * @mbggenerated
     */
    List<Message> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_message
     *
     * @mbggenerated
     */
    Message selectByPrimaryKey(Long messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Message record);
    
    void updateStatus(Long userId) throws Exception;
}