package com.bjwg.main.dao;

import com.bjwg.main.model.MyCoupon;
import com.bjwg.main.model.MyCouponExample;
import java.util.List;

public interface MyCouponDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int countByExample(MyCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long myCouponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int insert(MyCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int insertSelective(MyCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    List<MyCoupon> selectByExample(MyCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    MyCoupon selectByPrimaryKey(Long myCouponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MyCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MyCoupon record);
}