package com.bjwg.main.dao;

import com.bjwg.main.model.ServiceProtocol;
import com.bjwg.main.model.ServiceProtocolExample;
import java.util.List;

public interface ServiceProtocolDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int countByExample(ServiceProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long spId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int insert(ServiceProtocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int insertSelective(ServiceProtocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    List<ServiceProtocol> selectByExampleWithBLOBs(ServiceProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    List<ServiceProtocol> selectByExample(ServiceProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    ServiceProtocol selectByPrimaryKey(Long spId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ServiceProtocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ServiceProtocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ServiceProtocol record);
    
    /**
     * 根据类型编号查询协议
     * @param code
     * @return
     * @throws Exception
     */
    ServiceProtocol selectByType(String code) throws Exception;
}