package com.bjwg.main.dao;

import com.bjwg.main.model.UserExt;
import com.bjwg.main.model.UserExtExample;
import java.util.List;

public interface UserExtDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_ext
     *
     * @mbggenerated
     */
    int countByExample(UserExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_ext
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_ext
     *
     * @mbggenerated
     */
    int insert(UserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_ext
     *
     * @mbggenerated
     */
    int insertSelective(UserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_ext
     *
     * @mbggenerated
     */
    List<UserExt> selectByExample(UserExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_ext
     *
     * @mbggenerated
     */
    UserExt selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_ext
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_ext
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserExt record);
}