package com.bjwg.main.dao;

import com.bjwg.main.model.UserPreorder;
import com.bjwg.main.model.UserPreorderExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UserPreorderDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_preorder
     *
     * @mbggenerated
     */
    int countByExample(UserPreorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_preorder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("projectId") Long projectId, @Param("userId") Long userId);

    int selectCount(Long projectId);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_preorder
     *
     * @mbggenerated
     */
    int insert(UserPreorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_preorder
     *
     * @mbggenerated
     */
    int insertSelective(UserPreorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_preorder
     *
     * @mbggenerated
     */
    List<UserPreorder> selectByExample(UserPreorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_preorder
     *
     * @mbggenerated
     */
    UserPreorder selectByPrimaryKey(@Param("projectId") Long projectId, @Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_preorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserPreorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_user_preorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserPreorder record);
    
    /**
     * 联合查询，加载项目名称
     * @param example
     * @return
     * @throws Exception
     */
    List<UserPreorder> selectLoadNameByMap(Map<String, Object> map) throws Exception;
}