package com.bjwg.main.dao;

import com.bjwg.main.model.WalletChange;
import com.bjwg.main.model.WalletChangeExample;
import java.util.List;

public interface WalletChangeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_WALLET_CHANGE
     *
     * @mbggenerated
     */
    int countByExample(WalletChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_WALLET_CHANGE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long walletChangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_WALLET_CHANGE
     *
     * @mbggenerated
     */
    int insert(WalletChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_WALLET_CHANGE
     *
     * @mbggenerated
     */
    int insertSelective(WalletChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_WALLET_CHANGE
     *
     * @mbggenerated
     */
    List<WalletChange> selectByExample(WalletChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_WALLET_CHANGE
     *
     * @mbggenerated
     */
    WalletChange selectByPrimaryKey(Long walletChangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_WALLET_CHANGE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WalletChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BJWG_WALLET_CHANGE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WalletChange record);
}