package com.bjwg.main.dao;

import com.bjwg.main.model.WithDrawals;
import com.bjwg.main.model.WithDrawalsExample;
import java.util.List;

public interface WithDrawalsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int countByExample(WithDrawalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long withwradalsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int insert(WithDrawals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int insertSelective(WithDrawals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    List<WithDrawals> selectByExample(WithDrawalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    WithDrawals selectByPrimaryKey(Long withwradalsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WithDrawals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WithDrawals record);
}